id: AA4177A1B
title: Food Offering Prayer
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:42:14.157212
  last_modified_at: 2022-03-01 00:42:14.157216
