id: AA4177A1B
title: The Prayer that Swiftly Fulfils All Wishes (Sampa Nyur Drupma)
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:42:14.170445
  last_modified_at: 2022-03-01 00:42:14.170451
