id: AA4177A1B
title: Dedication (Sangye tenpa...)
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:42:14.155822
  last_modified_at: 2022-03-01 00:42:14.155829
