id: AA4177A1B
title: Prayer to the Omniscient Longchen Rabjam
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:42:14.166140
  last_modified_at: 2022-03-01 00:42:14.166148
