id: AA4177A1B
title: 'Rain of Wisdom, Love and Spiritual Power: A Guru Yoga of the Three Mañjughoṣas
  of the Land of Snow'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:42:14.167460
  last_modified_at: 2022-03-01 00:42:14.167464
