id: AA4177A1B
title: The Song of the Vajra
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:42:14.179158
  last_modified_at: 2022-03-01 00:42:14.179161
