id: AA4177A1B
title: Guru Yoga of the Great Omniscient One, Longchenpa
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:42:14.158603
  last_modified_at: 2022-03-01 00:42:14.158606
